apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: myapp-api-prefixes
  namespace: myapp-{{ sharedVars.env  }}
spec:
  stripPrefix:
    forceSlash: false
    prefixes:
      - /api/app
